In [1]:
include("Algorithm/utilities.jl")
include("Algorithm/branchAndBound.jl")
include("Algorithm/multiComponents.jl")

adjVarExplained (generic function with 1 method)

In [2]:
function multiOptimalSPCA(prob, k, ncomp)
	myprob = problem(copy(prob.data),copy(prob.Sigma))
	st = time()
	all_x = zeros(ncomp, size(myprob.Sigma,1))

	for rnd = 1:ncomp
		~, xVal, ~, ~, ~, ~, ~ = branchAndBound(myprob, k, outputFlag=0, timeCap = 30) ;
		all_x[rnd,:] = xVal

		myprob.Sigma = projectMatrix(myprob.Sigma, xVal)
	end

	return all_x, time()-st
end

multiOptimalSPCA (generic function with 1 method)

In [3]:
using CSV, Tables

In [4]:
Sigma = CSV.File("Data/Midgut-Cov.csv") |> Tables.matrix
genes = Sigma[:, 1]
Sigma = Matrix{Float64}(Sigma[:, 2:end])

572×572 Array{Float64,2}:
  40.9534    31.2565    34.6469    …  -2.03527   -0.713705    0.512494
  31.2565    32.4242    27.571        -1.56825   -0.549184    0.378342
  34.6469    27.571     31.5218       -1.84138   -0.436755    0.464107
  25.0434    26.7318    21.823        -1.34242   -0.547675    0.404733
  29.4154    22.5718    24.8996       -1.47321   -0.534021    0.677562
  -3.69799   -2.92796   -3.39221   …  -0.644177  -0.154674   -0.350434
  -3.50239   -3.87881   -1.98859      -0.953661   3.01733     0.515291
  28.8281    21.7605    25.0788       -1.58255   -0.236495    0.514843
  18.0784    19.2948    16.7394       -1.27494    0.0576934   0.0233051
 -10.9423    -8.40576   -9.79229       2.22265   -1.16009    -0.75856
   ⋮                               ⋱              ⋮          
  -0.544455  -1.03348   -0.506621     -0.170261  -0.10296     0.0498131
  -0.185831  -0.311415  -0.206015     -0.294287   0.0111389   0.0384985
   2.64305    0.450456   2.42567   …  -0.322882   0.021204

In [5]:
x, elapsed = multiOptimalSPCA(problem(sqrt(Sigma), Sigma), 10, 20)

 Nodes,   Left,  Objective,  Incumbent,       Gap(%),   Runtime(s)


 Nodes,   Left,  Objective,  Incumbent,       Gap(%),   Runtime(s)


 Nodes,   Left,  Objective,  Incumbent,       Gap(%),   Runtime(s)


 Nodes,   Left,  Objective,  Incumbent,       Gap(%),   Runtime(s)


 Nodes,   Left,  Objective,  Incumbent,       Gap(%),   Runtime(s)


 Nodes,   Left,  Objective,  Incumbent,       Gap(%),   Runtime(s)


 Nodes,   Left,  Objective,  Incumbent,       Gap(%),   Runtime(s)


 Nodes,   Left,  Objective,  Incumbent,       Gap(%),   Runtime(s)


 Nodes,   Left,  Objective,  Incumbent,       Gap(%),   Runtime(s)


 Nodes,   Left,  Objective,  Incumbent,       Gap(%),   Runtime(s)


 Nodes,   Left,  Objective,  Incumbent,       Gap(%),   Runtime(s)


 Nodes,   Left,  Objective,  Incumbent,       Gap(%),   Runtime(s)


 Nodes,   Left,  Objective,  Incumbent,       Gap(%),   Runtime(s)


 Nodes,   Left,  Objective,  Incumbent,       Gap(%),   Runtime(s)


 Nodes,   Left,  Objective,  Incumbent,       Gap(%),   Runtime(s)


 Nodes,   Left,  Objective,  Incumbent,       Gap(%),   Runtime(s)


 Nodes,   Left,  Objective,  Incumbent,       Gap(%),   Runtime(s)


 Nodes,   Left,  Objective,  Incumbent,       Gap(%),   Runtime(s)


 Nodes,   Left,  Objective,  Incumbent,       Gap(%),   Runtime(s)


 Nodes,   Left,  Objective,  Incumbent,       Gap(%),   Runtime(s)


([-0.4200738924718402 -0.35485635801533183 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], 560.1727540493011)

In [9]:
findall(genes .== "Dl")

1-element Array{Int64,1}:
 96

In [11]:
x[:, 96]

20-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.330273565874336
 0.0
 0.0
 0.0

In [17]:
genes[findall(x[17, :] .!= 0)]

10-element Array{Any,1}:
 "lncRNA:CR34335"
 "Ubx"
 "hdly"
 "Dl"
 "CG9021"
 "lncRNA:alphagamma-element:CR32865"
 "CG45060"
 "hdc"
 "Tet"
 "robo2"

In [22]:
Tables.table(x, header=genes) |> CSV.write("Midgut-K10-N20.csv")

"Midgut-K10-N20.csv"