In [3]:
using LinearAlgebra, CSV, Random, Tables, JLD

In [22]:
include("../Algorithm/utilities.jl")

refreshFile (generic function with 1 method)

In [18]:
data = load("../Data/communities.jld")["communities"]
# Matrix sqrt: via diagonalization and sqrt eigenvalues
raw_data = sqrt(data)';
n = size(data, 1);
N = n * n;
norms = data[1:n+1:N]
k = 5;
# All close.
maximum(abs.(raw_data * raw_data .- data))

6.140921104957897e-16

In [25]:
nodes = CSV.File("../Co-K5-Trace-Nodes.csv", header=false) |> Tables.matrix;
bounds = CSV.File("../Co-K5-Trace-Bounds.csv", header=false) |> Tables.matrix;

In [60]:
# node_id = 50
# node_id = 300
node_id = 40
y = nodes[:, node_id]
selected_data = findall(y .== 1)
i = sum(nodes[:, node_id] .== 1)
stillneed = k - i

2

In [54]:
bounds[:, node_id]

3-element Array{Float64,1}:
 0.19840666121229678
 0.3629025164807017
 0.4316969652057027

In [58]:
sum(norms[y .== 1]) + sum(selectsorted(norms .* (y .== -1), stillneed))

0.4316969652057027

In [62]:
s = maximum(svd(raw_data[:, selected_data]).S)
u = svd(raw_data[:, selected_data]).U[:, 1];
v = svd(raw_data[:, selected_data]).V[:, 1];
D = Matrix(1.0I, 101, 101)[:, selected_data];
s^2

0.14185918642419382

In [127]:
norm(raw_data[:, selected_data] * v)^2

0.14185918642419373

In [128]:
norm(u' * raw_data[:, selected_data])^2

0.1418591864241937

In [131]:
norm(data[:, selected_data][selected_data, :] * v)

0.14185918642419382

In [134]:
rank_one_term = (raw_data * u) .^ 2
rank_one_term[nodes[:, node_id] .== 0] .= 0
rank_one_term

101-element Array{Float64,1}:
 7.926078166037157e-6
 0.00042107519671213234
 0.010091876290498288
 0.0
 0.011482437882389994
 0.00013178020948110015
 0.0023632781250717723
 0.0009055802857870314
 0.0012990605554894848
 0.0016750788941365209
 ⋮
 0.0063246338140331565
 0.00029115092252889475
 0.0005201627269077583
 0.0008469155188951991
 3.40177036420949e-5
 0.0016327144857154394
 0.005953773016861563
 0.00018478862022754878
 0.0066479897694745995

In [135]:
# Upper bound on the contribution from adding one variable into ||E||^2.
# The upper bound comes from ||E||_F^2
# upper bounded by ||(I-uu')MD||_F^2. Also, we know that normCommunities
# has column norm of 1 for every variable.
# We should add another upper bound based on taking k columns from this
# row into ||E||_F.
residual_term = norms .- rank_one_term
residual_term[y .== 0] .= 0
residual_term

101-element Array{Float64,1}:
 0.016097164406534425
 0.02638209318953039
 0.054141001469726655
 0.0
 0.03214735697131307
 0.05392057454670922
 0.02172243664593466
 0.01970490065528001
 0.02642470524769024
 0.030432363176178794
 ⋮
 0.03542551701477036
 0.032597381433193566
 0.03968867072276389
 0.038444722591622994
 0.011947288809978047
 0.03961357916191083
 0.04651232744206663
 0.05757289255173794
 0.04763397466371458

In [149]:
function frobenius_rows_k(M, y)
    M = M .^ 2
    row_quantities = zeros(n)
    stillneed = k - sum(y .== 1)
    for row_index in 1:n
        if y[row_index] == 0
            continue
        end
        row = copy(M[row_index, :])
        row_sum = sum(row[y .== 1])
        row[y .== 1] .= 0
        if y[row_index] == -1
            row_sum += row[row_index]
            row[row_index] = 0
            row_stillneed = stillneed -1
        else
            row_stillneed = stillneed
        end
        row_sum += sum(sort(row, rev=true)[1:row_stillneed])
        row_quantities[row_index] = row_sum
    end
    row_quantities
end

frobenius_rows_k (generic function with 1 method)

In [150]:
# frobenius_rows_k(data - raw_data * u * u' * raw_data, y)

In [151]:
sum((y .== -1) .& (frobenius_rows_k(data - raw_data * u * u' * raw_data, y) .< residual_term))

9

In [71]:
lb_proj_nodes_extra = rank_one_term .>= sort(rank_one_term .* Array{Float64}(y .== -1))[end-stillneed+1]
lb_proj_nodes_extra = lb_proj_nodes_extra .& (y .== -1)
lb_proj_nodes = lb_proj_nodes_extra .| (y .== 1)
lb_proj = sum(rank_one_term[lb_proj_nodes])
lb_diag = maximum(svd(raw_data[:, lb_proj_nodes]).S) ^ 2

0.2732082054995253

In [76]:
lb_proj

0.2202679971348654

In [72]:
bounds[:, node_id]

3-element Array{Float64,1}:
 0.19840666121229678
 0.3629025164807017
 0.4316969652057027

In [102]:
lambda_1 = bounds[2, node_id]
lambda_2 = bounds[3, node_id] - lb_diag
lambda_2_lb = bounds[3, node_id] - lambda_1
lambda_2_lb, lambda_2

(0.06879444872500101, 0.15848875970617743)

In [101]:
# lambda_2 = svd(raw_data[:, selected_data]).S[2] + sum(selectsorted(residual_term, stillneed))

In [97]:
# Initialization. Loop until convergence.
residual_ub = lambda_2
# Contribution to Tr E < residual_ub
resid_var_sel = residual_term .<= residual_ub
residual_ub, sum((y .== -1) .& .~resid_var_sel)

(0.15848875970617743, 1)

In [144]:
# Contribution to ||E||^2 from the row sums (squared Frobenius norm)
E = data - (raw_data * u * u' * raw_data)
e_squared_program = mapslices(
    (row) -> sum(row[y .== 1].^2) + sum(selectsorted(row.^2 .* (resid_var_sel .& (y .== -1)), stillneed)),
    E,
    dims=2)[:, 1]

101-element Array{Float64,1}:
 0.0005554029068767853
 0.001300204404267114
 0.0038962818242294452
 0.003298492957263369
 0.0017288509633006
 0.0054001736522469816
 0.0009286853302516914
 0.000842925602719248
 0.0012082528446651646
 0.0016359927820874252
 ⋮
 0.0021348057339160486
 0.0019604950092779456
 0.0024554336107746088
 0.0023180086607039376
 0.0002738958392771004
 0.002322843602191724
 0.002787241818975897
 0.0036718053033598704
 0.0032810956650680912

In [151]:
# Upper bound on ||E||_F
lambda_2 = sqrt(sum(e_squared_program[y .== 1]) + sum(selectsorted(e_squared_program .* (y .== -1), stillneed)))

0.10793675401189105

In [146]:
sum(residual_term[y .== 1]) + sum(selectsorted(residual_term[y .== -1], stillneed))

0.24795709056878384

In [152]:
# Multiplier for 
mult_parallel = 1. / lambda_1
mult_perp = lambda_2 / (lb_proj - lambda_2)^2
mult_linearize = mult_parallel + mult_perp
linear_program = rank_one_term + mult_linearize * e_squared_program

101-element Array{Float64,1}:
 0.006289277913004189
 0.01512578995294894
 0.054157034543441396
 0.037304440673198415
 0.031034948386082922
 0.061205264447674636
 0.012866282756370652
 0.01043868177970345
 0.014963845396937299
 0.020177406008939646
 ⋮
 0.030468306358281173
 0.02246344921489454
 0.028289989325571935
 0.02706252903802565
 0.003131653872441306
 0.027903008972859585
 0.03747619808340141
 0.041711220502127375
 0.04375567505680993

In [153]:
# Linear program solution
sum(linear_program[y .== 1]) + sum(selectsorted(linear_program[y .== -1], stillneed))

0.28282067871658134

In [155]:
# Conservative program in case we cannot bound sin theta_perp.
linear_program_lam_2 = rank_one_term + mult_parallel .* e_squared_program
lambda_2 + sum(linear_program_lam_2[y .== 1]) + sum(selectsorted(linear_program_lam_2[y .== -1], stillneed))

0.33598481500982685

In [150]:
[sum((sort(rank_one_term, rev=true)[k] .> linear_program) .& (y .== -1)) sum(y .== -1)]

1×2 Array{Int64,2}:
 13  81